[package]

name = "twitter-api"
version = "0.6.0"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/gifnksm/twitter-api-rs"
description = "Unofficial Rust library for the Twitter API."
documentation = "https://gifnksm.github.io/twitter-api-rs"
edition = "2018"

[dependencies]
dirs = "3.0"
failure = "0.1"
failure_derive = "0.1"
oauth-client = { git = "https://github.com/ckampfe/oauth-client-rs.git" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
tokio = { version = "0.2", features = ["full"] }
